name: Update Circulating Supply

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  update-circulating-supply:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures the entire git history is checked out
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Calculate circulating supply and update JSON
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python calculate_circulating_supply.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add circulating_supply.json
        git commit -m "Update circulating supply" -a || echo "No changes to commit"
        git push
